# filepath: c:\Users\18258\my-project\mkdocs.yml
site_name: Epiphany's Notes
nav:
  - Home: index.md
  - About: about.md
  - Industrial Design:
    - 设计思维与表达: Industrial Design/设计思维与表达.md
    - 设计与艺术基础: Industrial Design/设计与艺术基础.md
    - 实体、结构与制造: Industrial Design/实体、结构与制造.md
    - 智能设计基础: Industrial Design/智能设计基础.md
    - Page 3: sections/page-3.md
  - Computer Science: computer/CSAPP.md
  - English: english/IELTS.md


theme:
  name: material
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.indexes
  logo: images/logo.png         # 网页左上角 logo
  favicon: images/favicon.png   # 浏览器标签页图标
  language: zh        # 设置默认语言为中文
  font:
    text: Roboto         # 正文和标题字体
    code: Roboto Mono    # 代码块字体
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换到夜间模式
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换到白天模式
extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 中文
      link: /zh/
      lang: zh